# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PDFConverterV2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SnapKit'
  pod 'PDFGenerator', '~> 3.1'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxAppState'
  pod 'RxGesture'
  pod 'Feedbacks'
  pod 'R.swift'
  pod 'RealmSwift', '~>10'
end
